#!/usr/bin/env python3
"""Rotate sops age keys and identity keys for a host.

Two subcommands:
  age-key <host> --age-key <current-keyfile>
    Generate a new age keypair, re-encrypt the host's secrets.yaml with only
    the new recipient, print a deploy checklist.

  identity <host> <label> --age-key <host-age-keyfile>
    Generate a new SSH keypair, replace <label>.key in the host's sops file
    (preserving all existing age recipients), write the pub to
    secrets/common/ssh/<host>/<label>.pub.

Requires: python3, sops 3.x, ssh-keygen, nix-shell (for age-keygen).
"""

import argparse
import os
import subprocess
import sys
import tempfile
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent


def _run(cmd, *, env=None, capture=True, stdin=None):
    r = subprocess.run(
        cmd,
        capture_output=capture,
        text=True,
        env=env,
        input=stdin,
    )
    return r


def _age_keygen(new_key_path: str) -> str:
    """Generate a new age keypair. Returns the public key string."""
    if os.path.exists(new_key_path):
        os.unlink(new_key_path)
    cmd = [
        "nix-shell", "-p", "age", "--run",
        f"age-keygen -o {new_key_path}",
    ]
    r = _run(cmd)
    if r.returncode != 0:
        sys.exit(f"age-keygen failed: {r.stderr.strip()}")
    # age-keygen writes the public key to stderr via nix-shell
    output = r.stdout + "\n" + r.stderr
    for line in output.splitlines():
        if line.startswith("Public key:"):
            return line[len("Public key:"):].strip()
    sys.exit(f"could not parse age public key from stdout/stderr")


def _ssh_keygen(priv_path: str, host: str, label: str):
    if os.path.exists(priv_path):
        os.unlink(priv_path)
    r = _run([
        "ssh-keygen", "-t", "ed25519", "-N", "",
        "-f", priv_path, "-C", host,
    ])
    if r.returncode != 0:
        sys.exit(f"ssh-keygen failed: {r.stderr.strip()}")


def ssh_keygen_pub(priv_path: str) -> str:
    r = _run(["ssh-keygen", "-y", "-f", priv_path])
    if r.returncode != 0:
        sys.exit(f"ssh-keygen -y failed: {r.stderr.strip()}")
    return r.stdout.strip()


def sops_decrypt(sops_file: Path, age_key: Path) -> str:
    env = {**os.environ, "SOPS_AGE_KEY_FILE": str(age_key)}
    r = _run(["sops", "-d", str(sops_file)], env=env)
    if r.returncode != 0:
        sys.exit(f"sops -d failed for {sops_file}: {r.stderr.strip()}")
    return r.stdout


def sops_encrypt(plaintext_yaml: str, recipients: list[str]) -> str:
    with tempfile.NamedTemporaryFile("w", suffix=".yaml", delete=False) as cfg:
        cfg.write("creation_rules:\n")
        cfg.write("  - path: .*\n")
        cfg.write("    age:\n")
        for r in recipients or ["*"]:
            cfg.write(f'      - "{r}"\n')
        cfg_path = cfg.name
    try:
        env = {**os.environ, "SOPS_CONFIG": cfg_path}
        with tempfile.NamedTemporaryFile("w", suffix=".yaml", delete=False) as tf:
            tf.write(plaintext_yaml)
            tmp_path = tf.name
        try:
            r = _run(["sops", "-e", tmp_path], env=env)
        finally:
            os.unlink(tmp_path)
        if r.returncode != 0:
            sys.exit(f"sops -e failed: {r.stderr.strip()}")
        return r.stdout
    finally:
        os.unlink(cfg_path)


def read_recipients(sops_file: Path) -> list[str]:
    """Age recipients are public metadata in the encrypted file."""
    data = yaml.safe_load(sops_file.read_text()) or {}
    sops_meta = data.get("sops") or {}
    age = sops_meta.get("age") or []
    return [entry["recipient"] for entry in age if entry.get("recipient")]


def _write_atomic(path: Path, content: str):
    tmp = path.with_name(path.name + ".tmp")
    tmp.write_text(content)
    os.replace(tmp, path)


def _label_key(label: str) -> str:
    return f"{label}.key"


def cmd_age_key(args) -> int:
    host = args.host
    age_key_path = Path(args.age_key)
    sops_file = (
        Path(args.sops_file)
        if args.sops_file
        else REPO_ROOT / "secrets" / "hosts" / host / "secrets.yaml"
    )
    if not sops_file.exists():
        sys.exit(f"sops file not found: {sops_file}")
    if not age_key_path.exists():
        sys.exit(f"age key not found: {age_key_path}")

    recipients = read_recipients(sops_file)
    if not recipients:
        sys.exit(f"no age recipients found in {sops_file}")

    new_key_path = None
    try:
        with tempfile.NamedTemporaryFile("w", delete=False, suffix=".key") as nk:
            new_key_path = nk.name

        new_pub = _age_keygen(new_key_path)
        print(f"new age public key: {new_pub}")

        plain = sops_decrypt(sops_file, age_key_path)
        data = yaml.safe_load(plain) or {}

        # Drop all sops metadata — it will be regenerated by sops -e
        data.pop("sops", None)

        new_plain = yaml.safe_dump(data, default_flow_style=False, sort_keys=False)
        enc = sops_encrypt(new_plain, [new_pub])

        _write_atomic(sops_file, enc)
        print(f"re-encrypted {sops_file} with new age recipient")

        verify = sops_decrypt(sops_file, Path(new_key_path))
        vdata = yaml.safe_load(verify) or {}
        if vdata.get("sops"):
            sys.exit("post-rotation verification failed: sops metadata leaked into plaintext")
        print("post-rotation verification: decrypt with new key OK")

        print(f"\nDeploy checklist for {host}:")
        print(f"  NEW AGE KEY:    {new_key_path} (MOVE TO host's sops.age.keyFile)")
        print(f"  DEPLOY:         nixos-rebuild --use-remote-sudo -H {host} switch")
        print(f"  VERIFY:         SOPS_AGE_KEY_FILE={new_key_path} sops -d {sops_file}")
        print(f"  CLEANUP:         rm {new_key_path} (after successful deploy)")
    finally:
        pass  # new_key_path is a deploy artifact; operator cleans up after deploy

    return 0


def cmd_identity(args) -> int:
    host = args.host
    label = args.label
    age_key_path = Path(args.age_key)
    sops_file = (
        Path(args.sops_file)
        if args.sops_file
        else REPO_ROOT / "secrets" / "hosts" / host / "secrets.yaml"
    )
    pub_out = Path(args.pub_out) if args.pub_out else REPO_ROOT / "secrets" / "common" / "ssh"
    if not sops_file.exists():
        sys.exit(f"sops file not found: {sops_file}")
    if not age_key_path.exists():
        sys.exit(f"age key not found: {age_key_path}")

    recipients = read_recipients(sops_file)
    if not recipients:
        sys.exit(f"no age recipients found in {sops_file}")

    key_name = _label_key(label)

    with tempfile.NamedTemporaryFile("w", delete=False, suffix=".key") as nk:
        priv_path = nk.name

    try:
        _ssh_keygen(priv_path, host, label)
        priv_text = Path(priv_path).read_text()
        pub = ssh_keygen_pub(priv_path)

        plain = sops_decrypt(sops_file, age_key_path)
        data = yaml.safe_load(plain) or {}
        data.setdefault(label, {})[key_name] = priv_text
        new_plain = yaml.safe_dump(data, default_flow_style=False, sort_keys=False)
        enc = sops_encrypt(new_plain, recipients)
        _write_atomic(sops_file, enc)
        print(f"re-encrypted {sops_file} with {key_name}")

        verify = sops_decrypt(sops_file, age_key_path)
        vdata = yaml.safe_load(verify) or {}
        stored = ((vdata.get(label) or {}).get(key_name))
        if stored != priv_text:
            sys.exit(f"post-rotation verification failed: {key_name} mismatch")
        print(f"post-rotation verification: {key_name} round-trip OK")

        pub_dir = pub_out / host
        pub_dir.mkdir(parents=True, exist_ok=True)
        pub_file = pub_dir / f"{label}.pub"
        pub_file.write_text(pub + "\n")
        print(f"wrote {pub_file}")

        print(f"identity rotated: {host}/{label} -> {pub_file}; rebuild {host}.")
    finally:
        if os.path.exists(priv_path):
            os.unlink(priv_path)

    return 0


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Rotate sops age keys and identity keys for a host"
    )
    sub = ap.add_subparsers(dest="command", required=True)

    p_age = sub.add_parser("age-key", help="rotate a host's sops age key")
    p_age.add_argument("host", help="nixos hostName")
    p_age.add_argument("--age-key", required=True, help="local copy of the host's CURRENT sops age keyfile")
    p_age.add_argument("--sops-file", help="override sops secrets.yaml path")

    p_id = sub.add_parser("identity", help="rotate an identity key (SSH etc.)")
    p_id.add_argument("host", help="nixos hostName")
    p_id.add_argument("label", help="identity label (e.g. ssh, build, borg:woody)")
    p_id.add_argument("--age-key", required=True, help="local copy of the host's sops age keyfile")
    p_id.add_argument("--sops-file", help="override sops secrets.yaml path")
    p_id.add_argument("--pub-out", help=f"override pub output dir (default: secrets/common/ssh)")

    args = ap.parse_args()

    if args.command == "age-key":
        return cmd_age_key(args)
    elif args.command == "identity":
        return cmd_identity(args)

    ap.print_help()
    return 1


if __name__ == "__main__":
    sys.exit(main())
