keys:
  - &admin_jerome age1yd27qq2ys4tyae08ncs09fqgma87asrd3kandkkyvdj0kgjn9v3qm3l0yu
  - &server_woody age1gjm3ntqmp5ulqdt5gswvprper9hkmnmupw9pl378q8v90m95nswsvklmdj
  - &server_pricklepants age1wrykyx4f8pwksclhj6jsamzjx676allyj8l3z09zjul2he6jhscssppu9l
  - &server_rex age1naetzgje6zlnd3pc5uat20wdnzc7kd9yf25m6my4flqvzjjfpvcqgrkw07
  - &server_buzz age1t0e4p99fqtgccrum94qa4w3kclg8n3xscvwsfc5pezlcf9ztwufs4gvzzn
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
        - *admin_jerome
        - *server_woody
        - *server_pricklepants
        - *server_rex
  - path_regex: secrets/woody/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
        - *admin_jerome
        - *server_woody
  - path_regex: secrets/pricklepants/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
        - *admin_jerome
        - *server_pricklepants
  - path_regex: secrets/rex/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
        - *admin_jerome
        - *server_rex
  - path_regex: secrets/buzz/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
        - *admin_jerome
        - *server_buzz
