keys:
  - &admin_jerome age1yd27qq2ys4tyae08ncs09fqgma87asrd3kandkkyvdj0kgjn9v3qm3l0yu
  - &bw_jerome age1ex3axxazzhsllzj0pqkdgjqnvzjmp8he2patv0k5wlzaacqwpfys8saxrq
  - &server_woody age1gjm3ntqmp5ulqdt5gswvprper9hkmnmupw9pl378q8v90m95nswsvklmdj
  - &server_woody_ssh age1d5x2redfne7ewmy9hxuws2vk0su3e7dnvgrkma2fv286xfcgc42qt36rql
  - &server_pricklepants age1wrykyx4f8pwksclhj6jsamzjx676allyj8l3z09zjul2he6jhscssppu9l
  - &server_rex age1naetzgje6zlnd3pc5uat20wdnzc7kd9yf25m6my4flqvzjjfpvcqgrkw07
  - &server_rex_ssh age1klmaxwfx895f99afm526wqd7apuumnky33unqlhx2j8s27pcu30qkjg49w
  - &server_buzz age1kugdd9sgaywmzg0k2d3lrutvq03shuy6lwc5cr6yjg5fzzzgjdvqzllptz
  - &server_lenny age1epwzgq42tx30zp99sep75qd7wy9ppgrl7k2gdualqq8aq8fhde8qu99nku
  - &server_jessie age1ryu9sln638lryj3yupm3p9swtqm986h3g84ezw43c9pqe8pw0g4qy7j2gt
  - &server_slinky age1zkm0j83lzkekgetkj9mlatmtg5p8dqqc6g0sf24pnw9dwkrytejq8t0sfc
  - &server_zurg age1wudmk6vrkdadznx92tdqa3s9sds6fyrw9xr5thu48k5h2qr3fd5qd0xy20
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *admin_jerome
          - *bw_jerome
          - *server_woody
          - *server_woody_ssh
          - *server_pricklepants
          - *server_rex
          - *server_rex_ssh
          - *server_buzz
          - *server_lenny
          - *server_jessie
          - *server_slinky
          - *server_zurg
  - path_regex: secrets/hosts/woody/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *admin_jerome
          - *bw_jerome
          - *server_woody
          - *server_woody_ssh
  - path_regex: secrets/hosts/pricklepants/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *admin_jerome
          - *bw_jerome
          - *server_pricklepants
  - path_regex: secrets/hosts/rex/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *admin_jerome
          - *bw_jerome
          - *server_rex
          - *server_rex_ssh
  - path_regex: secrets/hosts/buzz/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *admin_jerome
          - *bw_jerome
          - *server_buzz
  - path_regex: secrets/hosts/jessie/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *admin_jerome
          - *bw_jerome
          - *server_jessie
  - path_regex: secrets/hosts/lenny/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *admin_jerome
          - *bw_jerome
          - *server_lenny
  - path_regex: secrets/hosts/slinky/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *admin_jerome
          - *bw_jerome
          - *server_slinky
  - path_regex: secrets/hosts/zurg/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *admin_jerome
          - *bw_jerome
          - *server_zurg
  - path_regex: secrets/hosts/bully/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *admin_jerome
          - *bw_jerome
          - *server_zurg
  - path_regex: secrets/users/.+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *admin_jerome
          - *bw_jerome
          - *server_woody
          - *server_woody_ssh
          - *server_rex
          - *server_rex_ssh
          - *server_lenny
          - *server_slinky
          - *server_zurg
  - path_regex: secrets/services/.+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *admin_jerome
          - *bw_jerome
          - *server_woody
          - *server_woody_ssh
          - *server_pricklepants
          - *server_buzz
          - *server_jessie
          - *server_zurg
