{
  config,
  pkgs,
  lib,
  ...
}:{
  users.users.donquezz = {
    isNormalUser  = true;
    home  = "/home/donquezz";
    description  = "Jerome (DonQuezz)";
    extraGroups  = [ "wheel" "networkmanager" ];
    hashedPassword = "$y$j9T$xI3Gvnwn4Q900uL0HQZHp/$fl5oFfnZWZWBz.6gPxvciND13komHHAXDqq6Yfpjn17";
    uid = 1003;
    openssh.authorizedKeys.keys = [
	    ''ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKv3fhY8KfwN4GFxXpbWLCfNl4ZP+v+C59CIxXhj0SyB jerome@DESKTOP-B7K2FBB'' 
      ''ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICBx/L/AY2505t1Sj1yyugnK6Cf2QuIECx8kXxyoks3f jeromeb@nixos''
      ''ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHVNoVYUWvAghff/jL6lHW80p73L/eGWDMUDeJ4TpZeO jerome@DESKTOP-4SBFVCM''
      ''ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG8Wfyik+a9oL7hPG3T72maa14lYmI+k6fzqZP/t59MK Generated By Termius''
	    ''ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPMPF4zMcL0S5KGgVwrUMj5HVlZtVfdVR7gfQgnv3mpq jeromeb@woody''
     ''ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJFxSPRrleME4rxeabwWp6wA9C0ZMOjd+j6/Ej5JdyGJ Android''
	  ''ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHwH+gc41cAac4Rb4/rAA/XSUVyKrcWa2yofBoM/fXED j340m3@slinky''
	  ''ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMlQVBoAwlDM4QUrHFYE7tiHkAX7GmEJ7bZ6+jg/gTUE''
    ];
  }; 
}
